helpContents = [
    "Monta arquivo .qck em .fita",
    "Carrega .fita na memória",
    "Descarrega .fita da memória",
    "Adiciona processo",
    "Cria arquivo em disco",
    "Edita arquivo em disco",
    "Apaga arquivo em disco",
    "Limpa o terminal",
]

validCommands = [
    "assemble",
    "load",
    "unload",
    "run",
    "create",
    "edit",
    "delete",
    "clear",
]

keysToIgnore = [
    "ctrl+@",
    "ctrl+q",
    "ctrl+w",
    "ctrl+e",
    "ctrl+r",
    "ctrl+t",
    "ctrl+y",
    "ctrl+u",
    "ctrl+o",
    "ctrl+p",
    "ctrl+a",
    "ctrl+s",
    "ctrl+d",
    "ctrl+f",
    "ctrl+g",
    "ctrl+j",
    "ctrl+k",
    "ctrl+l",
    "ctrl+ç",
    "ctrl+z",
    "ctrl+x",
    "ctrl+c",
    "ctrl+v",
    "ctrl+b",
    "ctrl+n",
    "ctrl+m",
]